export const Application = {
	REQUEST_USERS_DATA: 'REQUEST_USERS_DATA',
	RECIEVE_USERS_DATA_SUCCESS: 'RECIEVE_USERS_DATA_SUCCESS',
	RECIEVE_USERS_DATA_FAILED: 'RECIEVE_USERS_DATA_FAILED',
	MODAL_OPENED: 'MODAL_OPENED',
	MODAL_CLOSED: 'MODAL_CLOSED',
	REQUEST_CREATE_USER: 'REQUEST_CREATE_USER',
	RECIEVE_CREATE_USER_SUCCESS: 'RECIEVE_CREATE_USER_SUCCESS',
	RECIEVE_CREATE_USER_FAILED: 'RECIEVE_CREATE_USER_FAILED',
	REQUEST_INITIALIZATION_INFO: 'REQUEST_INITIALIZATION_INFO',
	REQUEST_INITIALIZATION_INFO_SUCCESS: 'REQUEST_INITIALIZATION_INFO_SUCCESS',
	REQUEST_INITIALIZATION_INFO_FAILED: 'REQUEST_INITIALIZATION_INFO_FAILED',
	REQUEST_UPDATE_USER: 'REQUEST_UPDATE_USER',
	RECIEVE_UPDATE_USER_SUCCESS: 'RECIEVE_UPDATE_USER_SUCCESS',
	RECIEVE_UPDATE_USER_FAILED: 'RECIEVE_UPDATE_USER_FAILED',
	REQUEST_UPDATE_BALANCE: 'REQUEST_UPDATE_BALANCE',
	RECIEVE_UPDATE_BALANCE_SUCCESS: 'RECIEVE_UPDATE_BALANCE_SUCCESS',
	RECIEVE_UPDATE_BALANCE_FAILED: 'RECIEVE_UPDATE_BALANCE_FAILED',
	DETAILS_SELECTED: 'DETAILS_SELECTED',
	OPERATIONS_SELECTED: 'OPERATIONS_SELECTED',
	REQUEST_USER_INFO: 'REQUEST_USER_INFO',
	RECIEVE_USER_INFO_SUCCESS: 'RECIEVE_USER_INFO_SUCCESS',
	RECIEVE_USER_INFO_FAILED: 'RECIEVE_USER_INFO_FAILED',
	REQUEST_OPERATIONS_INFO: 'REQUEST_OPERATIONS_INFO',
	RECIEVE_OPERATIONS_INFO_SUCCESS: 'RECIEVE_OPERATIONS_INFO_SUCCESS',
	RECIEVE_OPERATIONS_INFO_FAILED: 'RECIEVE_OPERATIONS_INFO_FAILED',
	DATE_FROM_SELECTED: 'DATE_FROM_SELECTED',
	DATE_TO_SELECTED: 'DATE_TO_SELECTED',
	TYPE_SELECTED: 'TYPE_SELECTED',
	NEW_USERS_CLEARED: 'NEW_USERS_CLEARED',
	ERROR_CLOSED: 'ERROR_CLOSED'
}

export const Paginator = {
	PAGE_SELECTED: 'PAGE_SELECTED',
	PAGE_SKIPPED: 'PAGE_SKIPPED'
}

export const Filter = {
	DROPDOWN_OPENED: 'DROPDOWN_OPENED',
	DROPDOWN_CLOSED: 'DROPDOWN_CLOSED',
	TYPE_CHANGED: 'TYPE_CHANGED',
	FILTER_CHANGED: 'VALUE_CHANGED',
	FILTER_STARTED: 'SEARCH_STARTED',
	FILTER_ENDED: 'SEARCH_ENDED'
}

export const Users = {
	USER_SELECTED: 'USER_SELECTED',
}